name: build and deploy about-hugo/minimal-site

on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  pull_request:

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      
      - name: Install Ruby Dev                     
        run: sudo apt-get install ruby-dev
    
      - name: Install AsciiDoctor
        run: sudo gem install asciidoctor

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

#      - name: Download Theme
#        run: |
#          mkdir -p themes/hugo-geekdoc/
#          curl -L https://github.com/thegeeklab/hugo-geekdoc/releases/latest/download/hugo-geekdoc.tar.gz | tar -xz -C themes/hugo-geekdoc/ --strip-components=1
   
      - name: Build
        run: |
          hugo -b 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
